# Generated by Django 2.2 on 2019-04-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DesignationName', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
            ],
        ),
    ]
